### ISSUE TITLE
--help for verbs are not working

### ISSUE THREAD

**Issue by Kimi-Arthur** [gsscoder/commandline#204] opened 2015-07-20 03:03 UTC
(I believe I updated to the latest version 2.0.85-alpha)
Say I have a program "app", and a command "cp".

I can do a "app cp" which will produce a help page similar to "app help cp". I believe that when I do a "app cp --help", it should produce similar results, but instead it produces some exceptions like the following:

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at CommandLine.Infrastructure.ReflectionHelper.CreateDefaultImmutableInstance[Object] (System.Type[] constructorTypes) [0x00000] in <filename unknown>:0 
  at CommandLine.Core.InstanceBuilder+<>c__DisplayClass2d`1[System.Object].<Build>b__b () [0x00000] in <filename unknown>:0 
  at CommandLine.Core.InstanceBuilder.Build[Object] (CommandLine.Infrastructure.Maybe`1 factory, System.Func`3 tokenizer, IEnumerable`1 arguments, System.StringComparer nameComparer, System.Globalization.CultureInfo parsingCulture) [0x00000] in <filename unknown>:0 
  at CommandLine.Core.InstanceChooser.MatchVerb (System.Func`3 tokenizer, IEnumerable`1 verbs, IEnumerable`1 arguments, System.StringComparer nameComparer, System.Globalization.CultureInfo parsingCulture) [0x00000] in <filename unknown>:0 
  at CommandLine.Core.InstanceChooser.Choose (System.Func`3 tokenizer, IEnumerable`1 types, IEnumerable`1 arguments, System.StringComparer nameComparer, System.Globalization.CultureInfo parsingCulture) [0x00000] in <filename unknown>:0 
  at CommandLine.Parser+<>c__DisplayClassb.<ParseArguments>b__9 () [0x00000] in <filename unknown>:0 
  at CommandLine.Parser.MakeParserResult[Object] (System.Func`1 parseFunc, CommandLine.ParserSettings settings) [0x00000] in <filename unknown>:0 
  at CommandLine.Parser.ParseArguments (IEnumerable`1 args, System.Type[] types) [0x00000] in <filename unknown>:0 
  at CommandLine.ParserExtensions.ParseArguments[InfoCommand,CopyCommand,VerifyCommand] (CommandLine.Parser parser, IEnumerable`1 args) [0x00000] in <filename unknown>:0 
  at fileutil.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at CommandLine.Infrastructure.ReflectionHelper.CreateDefaultImmutableInstance[Object] (System.Type[] constructorTypes) [0x00000] in <filename unknown>:0 
  at CommandLine.Core.InstanceBuilder+<>c__DisplayClass2d`1[System.Object].<Build>b__b () [0x00000] in <filename unknown>:0 
  at CommandLine.Core.InstanceBuilder.Build[Object] (CommandLine.Infrastructure.Maybe`1 factory, System.Func`3 tokenizer, IEnumerable`1 arguments, System.StringComparer nameComparer, System.Globalization.CultureInfo parsingCulture) [0x00000] in <filename unknown>:0 
  at CommandLine.Core.InstanceChooser.MatchVerb (System.Func`3 tokenizer, IEnumerable`1 verbs, IEnumerable`1 arguments, System.StringComparer nameComparer, System.Globalization.CultureInfo parsingCulture) [0x00000] in <filename unknown>:0 
  at CommandLine.Core.InstanceChooser.Choose (System.Func`3 tokenizer, IEnumerable`1 types, IEnumerable`1 arguments, System.StringComparer nameComparer, System.Globalization.CultureInfo parsingCulture) [0x00000] in <filename unknown>:0 
  at CommandLine.Parser+<>c__DisplayClassb.<ParseArguments>b__9 () [0x00000] in <filename unknown>:0 
  at CommandLine.Parser.MakeParserResult[Object] (System.Func`1 parseFunc, CommandLine.ParserSettings settings) [0x00000] in <filename unknown>:0 
  at CommandLine.Parser.ParseArguments (IEnumerable`1 args, System.Type[] types) [0x00000] in <filename unknown>:0 
  at CommandLine.ParserExtensions.ParseArguments[InfoCommand,CopyCommand,VerifyCommand] (CommandLine.Parser parser, IEnumerable`1 args) [0x00000] in <filename unknown>:0 
  at fileutil.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by gsscoder** [comment] 2015-07-20 05:26
Mmm... It's weird, @Kimi-Arthur . Can I see your option classes? (PS: thanks for reporting).

**Comment by Kimi-Arthur** [comment] 2015-07-20 05:34
See https://gist.github.com/Kimi-Arthur/7223c23694db4686cb45 for details.

**Comment by gsscoder** [comment] 2015-07-20 14:21
`ParseArguments<T>` -> options only
`ParseArguments<T1, Tx, ...>` -> verbs only

The correct way to parse a single verb is to use the overload that accepts a param array of objects.

Can you post also your actual call to `ParseArguments`, please?

**Comment by gsscoder** [comment] 2015-07-20 14:31
OK, I've reproduced the issue in locally. Now I'll write a unit test and fix it. I'll warn you here.

**Comment by Kimi-Arthur** [comment] 2015-07-20 14:40
(Though you may have the case by now).
I just left out other commands here.

How I call it:

        static int Main(string[] args)
            => Parser.Default.ParseArguments<InfoCommand, CopyCommand, VerifyCommand>(args)
            .Return(
                (Command x) => x.Execute(),
                HandleParseFail);

**Comment by Kimi-Arthur** [comment] 2015-07-20 14:41
Also, as you may imagine, the "--version" will fail too.

**Comment by gsscoder** [comment] 2015-07-20 15:00
I wrote a failing test, fixing it and now I'll check it (manually) with version.

I'm pushing to nuget too.

**Comment by gsscoder** [comment] 2015-07-20 15:06
I can confirm that the issue is fixed with both `verb --help` and `verb --version` input.

Anyway, @Kimi-Arthur, please verify by yourself! :)

I think you've to wait until 2.0.93-alpha (just pushed) will be available as NuGet download.

Thanks again for reporting.

**Closed by gsscoder** 2015-07-20 15:06 UTC
