### ISSUE TITLE
Support .NET CORE 1.0

### ISSUE THREAD

**Issue by vlaldis** [gsscoder/commandline#348] opened 2016-09-13 11:13 UTC
Currently not working on .Net CORE 1.0 - netstandard1.4

**Comment by nemec** [comment] 2016-09-14 06:01
Duplicate of #237 

Support exists (for netstandard1.5, at least) in the master branch, but the owner of this project is the only one who can upload a new NuGet package.

**Closed by nemec** 2016-09-14 06:01 UTC
