### ISSUE TITLE
Mutually exclusive, non-optional arguments

### ISSUE THREAD

**Issue by StevenLiekens** [gsscoder/commandline#202] opened 2015-07-17 14:43 UTC
It's impossible right now to create sets of required options that are mutually exclusive.

````C#
[Option("foo", Required = true, MutuallyExclusiveSet = "foo")]
public string Foo { get; set; }

[Option("bar", Required = true, MutuallyExclusiveSet = "bar")]
public string Bar { get; set; }

[Option("baz")]
public string Baz { get; set; }
````

I'd expect to be able to do this...
>\> ConsoleApplication.exe --foo "123" --baz "xyz"

...or this...
>\>ConsoleApplication.exe --bar "123" --baz "xyz"

...but **not** this...
>\> ConsoleApplication.exe --foo "123" --bar "123" --baz "xyz"

Anyway, it doesn't work. The `Required` attribute doesn't respect the `MutuallyExclusiveSet` attribute.

>\> ConsoleApplication.exe --foo "123" --baz "xyz"

> ERROR(S):
  --bar required option is missing.

**Comment by gsscoder** [comment] 2015-07-18 04:00
@StevenLiekens, this is possible, since 2.0 kernel was rewritten and maybe something "escaped" from test coverage.

Thanks for reporting, I'll write a unit test to put this issue in evidence.

:+1:

**Comment by gsscoder** [comment] 2015-07-18 06:42
Fixed. Can you check if it's right now?

**Comment by gsscoder** [comment] 2015-07-18 06:50
cc/ @mizipzor @Thilas @nemec @gimmemoore 
If someone one check the fix to https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Core/SpecificationPropertyRules.cs#L44. I'll be glad!

Giacomo

**Comment by StevenLiekens** [comment] 2015-07-18 09:33
I forgot to mention that I was using the stable package. I'll try the alpha package now, but I don't know if it was actually broken in pre-release.

**Comment by StevenLiekens** [comment] 2015-07-18 10:14
It's working now in 2.0.81-alpha. Thank you!

Just a thought, but shouldn't the help text builder include set names?

Using my previous example, the error text is not clear about why this is an error.

>\> ConsoleApplication.exe --foo "123" --bar "123" --baz "xyz"
>
>ERROR(S):
>  Option 'foo' is defined along with an incompatible one.
>  Option 'bar' is defined along with an incompatible one.
>
>
>  --foo        Required.
>
>  --bar        Required.
>
>  --baz
>
>  --help       Display this help screen.
>
>  --version    Display version information.

I think that it would be useful to include incompatible options in the help text.

>  --foo        Required. Not compatible with --bar.
>
>  --bar        Required. Not compatible with --foo.

**Comment by gsscoder** [comment] 2015-07-18 10:55
@StevenLiekens, I'm not sure this could be useful, since set name are an internal abstraction of command line syntax...

I don't think these names could have a meaning for end user. Am I wrong?

_P.S.: I close the issue, because it's fixed -> anyway we can continue this discussion here._

**Closed by gsscoder** 2015-07-18 10:55 UTC
Labels: bug, priority

**Comment by gsscoder** [comment] 2015-07-18 13:31
@StevenLiekens, now is fixed!

I've added a test theory for completeness and I found that fix was not 100% correct. I've [rewritten the method](https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Core/SpecificationPropertyRules.cs#L45) in a clean and better way. All tests -> green! :triumph:

If you want, you can check it from sources or peek [2.0.85-alpha](https://www.nuget.org/packages/CommandLineParser/2.0.85-alpha) pushed to **NuGet** just now.

Thank you, again: maybe that this issue will be decisive to promote the **alpha** to **beta**!

**Comment by StevenLiekens** [comment] 2015-07-18 17:11
My worry is that the error message is too difficult to understand for the average user.

I think that if a user specifies both --foo and --bar, then the error handler should explain that --foo cannot be used with --bar in **plain English**.

This should be possible to implement based on set names, without ever printing the actual set name. If it isn't, then printing the set names is fine too.

**Comment by gsscoder** [comment] 2015-07-18 18:04
Yes, @StevenLiekens, you're right, but if we've to fix something is better fix it in a definitive way.

What do you think to add a descriptive text to each set?

I don't know where (not in options, because it could be repeated) but this could be the idea?

Or as you say in your sample, just try to format a better message.

**Comment by gsscoder** [comment] 2015-07-18 18:07
As you can see, I've opened a specific issue, so we can better track progresses. :) But I think we can continue discussion here. The issue is useful, so when fixed I can close it.

**Comment by gsscoder** [comment] 2015-07-20 06:11
@StevenLiekens, output is changed. Please check.

**Comment by StevenLiekens** [comment] 2015-07-20 11:54
That's perfect! Thanks.

**Comment by gsscoder** [comment] 2015-07-20 13:27
@StevenLiekens, I've to thank you for reporting these issues that helped make this library better.

Have a nice day! :+1:
