### ISSUE TITLE
Allow Min = 0

### ISSUE THREAD

**Issue by Sycobob** [gsscoder/commandline#176] opened 2015-06-27 01:58 UTC
For a collection option, it would be useful to allow the use to supply an empty set. Thus, I propose allowing Option.Min to be set to zero.

Ultimately, I'd like to be able to differentiate between

1. MyUtility <other options>
2. MyUtility <other options> --ToggleRefreshRate
3. MyUtility <other options> --ToggleRefreshRate 60 120

In 1, user has not specified the command, so do nothing.
In 2, user has specified the command, but no values, so use defaults (determined at runtime).
In 3, user has specified the command and a set of values, use specified values.

It makes sense for the value of the IEnumerable<int> property associated with ToggleRefreshRate  to be null, empty, and { 60, 120 } respectively, which is not currently possible.

Also necessary for this is the ability to know when the option is not provided at all, as in case 1. Perhaps through DefaultValue = null? (See #175)

**Comment by gsscoder** [comment] 2015-06-27 05:04
@Sycobob,
example is clear... But what was the problem, you can't set ``Min=0``?

This why ``Min`` is enforced constraint. For example, saying ``Min=3``, means: or you give me a minimum of **3 elements** or parser will fail!

Here I think is at least quoted: https://github.com/gsscoder/commandline/wiki/Latest-Version#capturing-sequences.

I can suggest how to get the behaviour you explained:
```csharp
class Options {
  [Option]
  public bool ToggleRefreshRate { get; set; }

 [Value(0, Max=2)]
 public IEnumerable<int> RefreshRate { get; set; }
}
```
Anyway these solution leave too much flexibility like define ``--ToggleRefreshRate`` after its values. A better could be use two options:
```csharp
class Options {
 [Option("on")]
 public bool TogleRefreshRate { get; set; }

  [Option(Max=2)]
  public Enumerable<int> RefreshRate { get; set; }
}
```
Allows this:
```bash
app                                         # TogleRefreshRate = false, RefreshRate = new int[] {}
app --on                                 # TogleRefreshRate = true, RefreshRate = new int[] {}
app --on --refreshrate 10 20  # TogleRefreshRate = true, RefreshRate = new int[] {10, 20}
```

**Comment by Sycobob** [comment] 2015-06-27 05:18
> But what was the problem, you can't set Min=0?

Correct. Setting Min = 0 doesn't allow an empty sequence. e.g. `MyUtility -RefreshRate` yields

    ERROR(S):
      Option 'ToggleRefresh, r' has no value.

Your example with 2 Options is functional, but needing 2 options for one job is not intuitive or simple.

**Comment by gsscoder** [comment] 2015-06-27 05:55
Solutions proposed didn't helped.

The behaviour is correct you say `Min=0` that means: don't accept values. In that way there's no possibility to make the parser happy.
**The is an expected behaviour.**

A correct objection could be: why I'm allowed to do so... In fact I'm evaluating to raise an exception when `Min=0` (or also `Max=0`): these constraint must be valued when specified.

**Comment by Sycobob** [comment] 2015-06-27 15:32
As I said, the solutions proposed are functional, but awkward. I just want to be able to have a collection where the values are optional. I can use a helper option to do it, but it just seems unnecessary.

I understand it's expected behaviour, I guess my issue is that perhaps there is a *better* expected behaviour? Intuitively, saying `Min = 0` means "specifying values is optional, you are allowed to use the option with no values".

`Max = 0` does indeed seem erroneous. If you can never specify any values, being a collection makes no sense.

**Comment by gsscoder** [comment] 2015-06-27 16:06
@Sycobob,
these are points of view... You're not forced to enforce `Min` or `Max` when mapping to sequence, hence `Min=0` is meaningless like `Max=0`. (I meaningless to current specification).

As said in 2.0.x-pre specific docs, setting `Min=1, Max=1` overlaps with `Required=true` but what changes in this scenario is the `Error` you get in your `Parser<T>.Errors` instance.

Setting `Min=0` will never make the parser happy and the only better thing to do (as code fix), could raise an exception. To be clear is something wrong in development cycle not at runtime: is like setting `Min, Max` in a scalar value: you get an exception as developer, not as application user! :open_mouth:

Coming back to your problem... I think that you can easily solve it redefining semantic of your command line arguments. You're trying to use a single option to express two concepts:
- being able to input a refresh rate
- being able to supply value to refresh rate if set

If I can give a little suggestion, just rethink in terms of data you need and then come back to define your command line syntax.

Feel free to add comments, but technically I've to close the issue since this is currently (and correctly) how the parser works.

Thanks for using this project!

**Closed by gsscoder** 2015-06-27 16:06 UTC
Labels: question

**Comment by gsscoder** [comment] 2015-06-27 16:25
I'm currently working on a dev branch to raise exception when min, max are set 0.

**Comment by gsscoder** [comment] 2015-06-27 16:56
Done! :+1:

**Comment by mizipzor** [comment] 2015-06-27 17:22
For completeness, can we link the solving commit here?

**Comment by gsscoder** [comment] 2015-06-27 17:58
This was not done, because the change was done for problem raised from discussion. Not exactly the issue.
